
services:
  - type: web
    name: thirdparty-backend
    env: node
    plan: free
    buildCommand: cd server && npm install && npm run build
    startCommand: cd server && npm run start
    rootDir: server

  - type: web
    name: thirdparty-frontend
    env: static
    plan: free
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/dist
